version: '2'

services:

    puffin:
        build: .
        image: puffinrocks/puffin
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/usr/src/app
        depends_on:
            - puffindb
            - dns
            - mailhog
        command: ["up", "-r"]
        environment:
            - VIRTUAL_HOST=puffin.localhost
            - VIRTUAL_PORT=8080
        ports: 
            - "8080:8080"
        networks:
            - front
            - back
            - default

    puffindb:
        image: postgres
        ports:
            - 5432
        networks:
            back:
    
    dns:
        image: puffinrocks/dns
        ports: 
            - 53:53/udp
        networks:
            back:
        tmpfs:
            - /run
            - /tmp

    dnsfix:
        image: sequenceiq/alpine-dig
        entrypoint: ["/bin/sh", "-c", "echo nameserver `dig +short dns` > /etc/resolv.conf"]
        network_mode: "service:puffin"

    mailhog:
        image: mailhog/mailhog
        ports: 
            - "8025:8025"
            - 1025
        environment:
            - VIRTUAL_HOST=mailhog.localhost
            - VIRTUAL_PORT=8025
        networks:
            front:
            back:

networks:
    
    front:
    back:
