version: '2'

services:
 
    main:
        image: loomchild/ghost
        ports: 
            - 2368
        volumes: 
            - main_data:/var/lib/ghost
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=2368
        networks:
            - front
            - back
            - default

volumes:
    main_data:

networks:
    front:
        external: 
            name: "network_front"
    back:
        external:
            name: "network_back"
