version: '2'

services:

    main:
        image: rocket.chat:latest
        depends_on:
            - db
        ports:
            - 3000
        volumes: 
            - main_data:/app/uploads
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
            - MAIL_URL=smtp://mail:25
        networks:
            - front
            - back
            - default

    db:
        image: loomchild/mongo
        volumes: 
            - db_data_db:/data/db
            - db_data_configdb:/data/configdb

volumes:
    main_data:
    db_data_db:
    db_data_configdb:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
