version: '2'

services:
 
    main:
        image: loomchild/flarum
        depends_on:
            - db
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        networks:
            - front
            - default

    db:
        image: loomchild/mariadb
        ports: 
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flarum
            MYSQL_USER: flarum
            MYSQL_PASSWORD: flarum
        volumes: 
            - db_data:/var/lib/mysql

volumes:
    main_data:
    db_data:

networks:
    front:
        external:
            name: "puffin_front"
