version: '2'

services:

    main:
        image: wordpress
        depends_on:
            - db
        ports:
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_PASSWORD=wordpress
        networks:
            - front
            - default
    
    db:
        image: loomchild/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
        volumes: 
            - db_data:/var/lib/mysql

volumes:
    main_data:
    db_data:

networks:
    front:
        external:
            name: "network_front"
